spring:
  session:
    redis:
      namespace: ucup:edge
    timeout: 10m
  cloud:
    gateway:
      redis-rate-limiter:
        include-headers: false
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
          - id: catalog-route
            uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
            predicates:
              - Path=/books/**
            filters:
              - name: CircuitBreaker
                args:
                  name: catalogCircuitBreaker
                  fallbackUri: forward:/catalog-fallback
          - id: order-route
            uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
            predicates:
              - Path=/orders/**
            filters:
              - name: CircuitBreaker
                args:
                  name: orderCircuitBreaker
      default-filters:
        - SaveSession
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s
server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000

  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 5
logging:
  level:
    io.github.resilience4j: debug